### ISSUE TITLE
Error on pushing image to GCR

### ISSUE THREAD

**Issue by vasyan1992** [GoogleContainerTools/kaniko#1791]
**Actual behavior**
Getting an error on kaniko with GCR after latest update (version 28a6bdce78a5f5cb09cc4cc650595721554eef6b-debug
1.7.0-debug)

**Expected behavior**
image a0c96b4edcaeee437243484f5880833518d06551-debug is OK (ver 1.6.0-debug)

**To Reproduce**
printf $REGISTRY_ACCESSKEY > ${CI_PROJECT_DIR}/gcr.json
 /kaniko/executor --context $CI_PROJECT_DIR --dockerfile ./Dockerfile --destination ${IMAGE}

**Additional Information**
 - Error:
 error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "eu.gcr.io/***********/****************:*****": creating push check transport for eu.gcr.io failed: GET https://eu.gcr.io/v2/token?scope=repository%3A***********%2F*****%3Apush%2Cpull&service=eu.gcr.io: UNAUTHORIZED: Not Authorized.
 - Kaniko Image 28a6bdce78a5f5cb09cc4cc650595721554eef6b-debug
1.7.0-debug
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

**Comment by rushilsrivastava** [comment]
Seeing this error as well.

**Comment by Foxinou35** [comment]
Same issue here :/ Workaround worked thanks
PS : lost several hours checking and checking the roles on my service account ^^

**Comment by gmega** [comment]
Same here, looks like this could be a regression of #1242.

**Comment by tejal29** [comment]
Thanks fix is the way! https://github.com/GoogleContainerTools/kaniko/pull/1794

**Comment by Tarang** [comment]
is this live yet?

**Comment by nicolas-goudry** [comment]
Same issue here.
A workaround to use 1.7.0 with GCR using a service account is to use the `.docker/config.json` method providing following credentials:

```shell
$ mkdir -p /kaniko/.docker
$ echo "{\"auths\":{\"gcr.io\":{\"auth\":\"$(echo -n _json_key:$(cat service-account-key.json) | base64 | tr -d "\n")\"}}}" > /kaniko/.docker/config.json
```

**Comment by stefpb** [comment]
Keeping version 1.6 is now the answer? Why no one revert this 1.7 version?

**Comment by imjasonh** [comment]
> Keeping version 1.6 is now the answer? Why no one revert this 1.7 version?

The current `:latest` used by `gcloud` points to `1.6.0`, since there was a bug in `1.7.0`.

**Comment by kaaboaye** [comment]
Current latest works for me. I think it was fixed.

**Comment by rwong2888** [comment]
@stefpb , @imjasonh 

I was able to use 1.7.0 by mounting a docker config using the SA creds

https://issueexplorer.com/issue/GoogleContainerTools/kaniko/1791#10012106

https://webcache.googleusercontent.com/search?q=cache:jx9iGg75zJcJ:https://issueexplorer.com/issue/GoogleContainerTools/kaniko/1791+&cd=1&hl=en&ct=clnk&gl=us

> nicolas-goudry wrote this answer on 2021-10-21
Same issue here.
A workaround to use 1.7.0 with GCR using a service account is to use the .docker/config.json method providing following credentials:
$ mkdir -p /kaniko/.docker
$ echo "{\"auths\":{\"gcr.io\":{\"auth\":\"$(echo -n _json_key:$(cat service-account-key.json) | base64 | tr -d "\n")\"}}}" > /kaniko/.docker/config.json

@Keramblock latest got reverted to 1.6.0 due to issues

**Comment by hudac** [comment]
Also tested v1.8.0 and v1.8.1, same issue. Reverted back to v1.6.0, now it works :/

**Comment by kdaghay** [comment]
Using 1.9.1 still an issue. Used @nicolas-goudry's suggestion which works.

https://github.com/GoogleContainerTools/kaniko/issues/1791#issuecomment-948393053
> Same issue here. A workaround to use 1.7.0 with GCR using a service account is to use the `.docker/config.json` method providing following credentials:
> 
> ```shell
> $ mkdir -p /kaniko/.docker
> $ echo "{\"auths\":{\"gcr.io\":{\"auth\":\"$(echo -n _json_key:$(cat service-account-key.json) | base64 | tr -d "\n")\"}}}" > /kaniko/.docker/config.json
> ```

**Comment by aaron-prindle** [comment]
Can anyone here comment on if this issue is still occuring for them w/ the latest version of Kaniko `v1.12.1` and any specific repro steps that can be done to replicate this?  I am using a GCR w/ Kaniko for `gcr.io` domain using both a json service account key and Workload Identity and Kaniko is successfully uploading images in both cases.  Happy to dig into this more if someone else here can provide additional repro details.  Thanks

**Comment by hudac** [comment]
I can't reproduce this issue anymore. We are using v1.9.2 (and testing v1.12), no issue so far.

In our case, this was a configuration issue. We are using GCR auth via workload identity. Till v1.6 we had to provide a Docker config file (`/kaniko/.docker/config.json`), like this one:
```
{
  "credHelpers": {
    "eu.gcr.io": "gcr",
    "gcr.io": "gcr"
  }
}
```

Since at least v1.8 (maybe even v1.7) you don't need, actually you **cannot** have this Docker config file anymore. If this file is present, Kaniko v1.8 or newer fails with an auth error as reported in this issue. And vice versa, v1.6 does not work without the config file above.

If you are using the newest version of Kaniko with GCR and workload identities, omit the Docker config file. Keeping an empty one `{}` also works.

**Comment by aaron-prindle** [comment]
Thanks @hudac, closing this issue as I believe this is resolved @ HEAD
